### ISSUE TITLE
recover_poly_from_samples doesn't return errors when too many samples are missing

### ISSUE THREAD

**Issue by nazar-pc** [sifraitech/rust-kzg#195]
I tried version from `blst_from_scratch` and it returned success, but recovered nothing.

Is this expected behavior or a bug?

**Comment by sauliusgrigaitis** [comment]
My general attitude is that a cryptography library should return meaningful errors in such situations. So if possible the library should check the input and return a meaningful error instead of "successfully" calculating some junk.

**Comment by nazar-pc** [comment]
It already collects missing indices into a vector, we can check the vector length and if it is too big return an error. WDYT?

**Comment by sauliusgrigaitis** [comment]
This could work. If you would like to open a PR for this please also add a test [here](https://github.com/sifraitech/rust-kzg/blob/main/kzg-bench/src/tests/recover.rs) and hook it to at least `blst-from-scratch` crate [here](https://github.com/sifraitech/rust-kzg/blob/main/blst-from-scratch/tests/recovery.rs)
