### ISSUE TITLE
Allow getting polynomial from recover_poly_from_samples

### ISSUE THREAD

**Issue by nazar-pc** [sifraitech/rust-kzg#200]
We have a use case at Subspace that requires a polynomial reconstruction. Despite the name `recover_poly_from_samples` though, https://github.com/sifraitech/rust-kzg/blob/7eb52ca97576ea1eefe4dd2165f224c916f8c862/blst-from-scratch/src/recovery.rs#L169 is where reconstructed polynomial is then turned back into data and in our case we'll be converting data into polynomial, wasting computation on two extra FFTs.

What do you think about having separate functions for reconstructing data (what current implementation does) and polynomial itself (what I described above) separately?

**Comment by sauliusgrigaitis** [comment]
I think that it's OK to have separate functions. It's probably best to refactor it slightly so that those separate functions doesn't repeat the code.

**Comment by nazar-pc** [comment]
I can do that, just wanted to make sure it is a welcome potential change

**Comment by nazar-pc** [comment]
I see in addition to that function (which optionally supports parallelism) there is also `<FsPoly as PolyRecover<FsFr, FsPoly, FsFFTSettings>>::recover_poly_from_samples()` with basically the same functionality, but no parallelism and slightly different code.

Is it intentional, should be de-duplicated, should standalone function be removed?
